---
    name: Deploy to stagging
    on:
      push:
        branches:
          - production
    jobs:
    
      redeploy-everything:
        runs-on: ubuntu-latest
        name: Deploying the everything to production
        steps:
         - run: |
              echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
              chmod 700 ~/ssh_key
              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@13.126.99.149
              ssh -i ~/ssh_key ubuntu@13.126.99.149 << 'EOF'
              cd deploy-next-app && git pull production
              export PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
              pnpm install
              pnpm run build
              pm2 restart http-server 
              pm2 restart ws-server 
              pm2 restart web 
              EOF
    