---
    name: Deploy to production
    on:
      push:
        branches:
          - production
    jobs:
    
      redeploy-everything:
        runs-on: ubuntu-latest
        name: Deploying the everything to production
        steps:
         - run: |
              echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
              mkdir -p /home/runner/.ssh
              touch /home/runner/.ssh/known_hosts
              chmod 700 ~/ssh_key
              echo "${{secrets.KNOWN_HOSTS}}" $> /home/runner/.ssh/known_hosts
              ssh -i ~/ssh_key ubuntu@13.126.99.149 -t "ls -la"
    