---
    name: Deploy to stagging
    on:
      push:
        branches:
          - main
    jobs:
    
      redeploy-everything:
        runs-on: ubuntu-latest
        name: Deploying the everything to staggging
        steps:
         - run: |
              echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
              mkdir -p /home/runner/.ssh
              ls /home/runner/.ssh
              touch /home/runner/.ssh/known_hosts
              chmod 700 ~/ssh_key
              echo "${{secrets.KNOWN_HOSTS}}" $> /home/runner/.ssh/known_hosts
              ssh -i ~/ssh_key ubuntu@13.126.70.90 << 'EOF'
              cd deploy-next-app && git pull
              ls -la
              export PATH=/root/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
              pnpm install
              pnpm run build
              pm2 restart http-server 
              pm2 restart ws-server 
              pm2 restart web >>
    