---
    name: Deploy to stagging
    on:
      push:
        branches:
          - main
    jobs:
      redeploy-everything:
        name: Deploying the everything to staggging
        steps:
          - name: SSH into server
          - run: |
              echo ${{secret.SSH_PRIVATE_KEY}} &> ~/ssh_key
              ssh -i ~/ssh_key ubuntu@13.126.70.90
              cd deploy-next-app && git pull
              pnpm install
              pnpm run build
              pm2 restart http-server 
              pm2 restart ws-server 
              pm2 restart web
    