---
    name: Deploy to stagging
    on:
      push:
        branches:
          - main
    jobs:
    
      redeploy-everything:
        runs-on: ubuntu-latest
        name: Deploying the everything to staggging
        steps:
         - run: |
              echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
              ssh -i ~/ssh_key ubuntu@13.126.70.90
              cd deploy-next-app && git pull
              pnpm install
              pnpm run build
              pm2 restart http-server 
              pm2 restart ws-server 
              pm2 restart web
    